config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

 get 'sessions/new'

 get 'sessions/create'

 get 'sessions/destroy'
get "login" => "sessions#new", :as => "login"
delete 'logout' => "sessions#destroy", :as => "logout"
resources :sessions

  resources :reviews

  resources :people

  resources :sales

  resources :products

  get 'home/index'

  get 'home/search'
post "home/search"
  get 'home/about'

  get 'home/contact'










root 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
# Adapted from Learning Rails 3

  # call the store_photo method after the database record has been saved.
  after_save :store_photo

  # sets the directory name of where the images are stored. The
  # join utility concatenates the file name segments specific to the platform
  # (e.g. windows uses back-slashes to connect filename segments) 
  PHOTO_STORE = Rails.root.join 'public', 'photo_store'

  # allows a controller to assign the file_data to the photo field
  # 'photo' will serve as a virtual attribute for the data model
  def photo=(file_data)
    unless file_data.blank?
      @file_data = file_data 
      self.extension = file_data.original_filename.split('.').last.downcase
    end
  end

  # get the file name based on the record's id and the image extension
  def photo_filename
    File.join PHOTO_STORE, "#{id}.#{extension}"
  end

  # get the location of the photo so that it can be referenced in a view
  def photo_path
    "/photo_store/#{id}.#{extension}"
  end

  def has_photo?
    File.exists? photo_filename
  end

private

  # this utility method actually saves the image's data to the file
  def store_photo
    if @file_data
      # create folder if it doesn't exist yet
      FileUtils.mkdir_p PHOTO_STORE
      File.open(photo_filename, 'wb') do |f|
        f.write(@file_data.read)
      end

      # prevents saving the same image twice
      @file_data = nil
    end
  end
   
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:proudctname, :description, :price, :photo)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, html: { multipart: true }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :proudctname %><br>
    <%= f.text_field :proudctname %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product, class: 'show' %>
<br>
<br> 
<%= link_to 'Back', product_path, class: 'back'%>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Proudctname</th>
      <th>Description</th>
      <th>Price</th>
      <th>Photo</th>
      <th>Buy</th>
      <th colspan="3">Show </th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.proudctname %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%  if product.has_photo? %>
            <%= image_tag product.photo_path, size:'50x50' %>
            <% else %>
            No photo.
            <% end %></td>
            <td> <%= link_to "Buy", new_sale_path(:product_id => product) %> </td>
        <td><%= link_to 'Show', product, class: 'show' %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New', new_product_path, class: 'new' %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Proudctname:</strong>
  <%= @product.proudctname %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Photo:</strong><br />
  <% if @product.has_photo? %>
    <%= image_tag @product.photo_path, size:'250x250' %>
  <% else %>
    No photo.
  <% end %>
</p>



<%= link_to 'Edit', @product, class: 'edit' %>
<br>
<br> 
<%= link_to 'Back', products_path, class: 'back'%>