config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

 get 'sessions/new'

 get 'sessions/create'

 get 'sessions/destroy'
get "login" => "sessions#new", :as => "login"
delete 'logout' => "sessions#destroy", :as => "logout"
resources :sessions

  resources :reviews

  resources :people

  resources :sales

  resources :products

  get 'home/index'

  get 'home/search'
post "home/search"
  get 'home/about'

  get 'home/contact'










root 'home#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  # Each sale belongs to only 1 person
  belongs_to :person

  # Each sale belongs to only 1 product
  belongs_to :product

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
	@customer_choice = Person.order("lastname").collect do |c| [c.lastname + ", " + c.firstname, c.id] end
	@product_choice = Product.order("proudctname").collect do |p| [p.proudctname + " - " + p.price.to_s, p.id] end
	@sale.product_id = params["product_id"] #Product ID received as parameter
	@sale.person_id = session[:user_id] #Person ID obtained from session ID - person's ID who's logged-in
	@sale.saledate = Time.now # Today's date
	@sale.saleprice = Product.find_by_id(params["product_id"]).price #Getting cost from Product's table
  end

  # GET /sales/1/edit
  def edit
	@customer_choice = Person.order("lastname").collect do |c| [c.lastname + ", " + c.firstname, c.id] end
	@product_choice = Product.order("proudctname").collect do |p| [p.proudctname + " - " + p.price.to_s, p.id] end
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:person_id, :product_id, :saledate, :saleprice)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.select :person_id, @customer_choice %>
  </div>


  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.select :product_id, @product_choice %>
  </div>
  <div class="field">
    <%= f.label :saledate %><br>
    <%= f.date_select :saledate %>
  </div>
  <div class="field">
    <%= f.label :saleprice %><br>
    <%= f.text_field :saleprice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<h1>Listing sales</h1>

<table>
  <thead>
    <tr>
      <th>Saledate</th>
      <th>Saleprice</th>
      <th colspan="2"> Show</th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.saledate %></td>
        <td><%= sale.saleprice %></td>
        <td><%= link_to 'Show', sale %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Saledate:</strong>
  <%= @sale.saledate %>
</p>

<p>
  <strong>Saleprice:</strong>
  <%= @sale.saleprice %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>