config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

 get 'sessions/new'

 get 'sessions/create'

 get 'sessions/destroy'
get "login" => "sessions#new", :as => "login"
delete 'logout' => "sessions#destroy", :as => "logout"
resources :sessions

  resources :reviews

  resources :people

  resources :sales

  resources :products

  get 'home/index'

  get 'home/search'
post "home/search"
  get 'home/about'

  get 'home/contact'










root 'home#index'

end

app/views/layouts/_header.html.erb
<div id="header" >
<table>
	<tr>
     <td>
	   <table id="searchbar">
	     <tr>
			<td id="search-login"><%= image_tag 'weed-coffee-logo.png', :size => "100x100"%> </td>
            <td><h1></h1>
			<td align="right">
		<%= form_tag :controller => 'home', :action => 'search' do %>
			<p>Search: <%= text_field_tag 'searchinput' %> </p>
			<%= button_to 'Search', home_search_path, :method => :get%>
		<% end %>
		</td>

		<td>
		<% if session[:user_id].nil? %>
				 <%= link_to "New Customer", new_person_path %>
				 <%= button_to 'Login', login_path, :method => :get %>
				<% else %>
					Hello <%= Person.find(session[:user_id]).firstname %> !
					<%= button_to 'Logout', logout_path, :method => :delete %>
				<% end %>
	     </tr>
	   </table>

</td></tr>
<tr>
	<td>
	<table id= "navbar">
		<tr>
			<td><%= link_to_unless_current "Home", home_index_path %>	</td>
			<td><%= link_to_unless_current "About", home_about_path %> </td>
			<td><%= link_to_unless_current "Contact", home_contact_path %></td>
			<td><%= link_to_unless_current "Products", products_path %> </td>
			<td><%= link_to_unless_current "Customers", people_path %> </td>
			<td><%= link_to_unless_current "Reviews", reviews_path %> </td>
			<td><%= link_to_unless_current "Sales", sales_path %> </td>

		</tr>
	</table>
	</td>
</tr>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <tr>
    <td height="100"> <%= render 'layouts/header' %> </td> 
  </tr>
    <div id="main-container" class="container">
      <div class="row">
        <div id="sidebar" class="col-xs-3">
          <!-- sidebar content -->
        </div>
        <div id="content" class="col-xs-9">
        	<%= yield %>
          <!--  main content -->
        </div>
      </div>
    </div>



</body>
</html>